# Generated by Django 5.0 on 2026-04-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="suspended_until",
            field=models.DateTimeField(
                blank=True,
                help_text="If set, user is suspended until this datetime",
                null=True,
            ),
        ),
    ]
