# Generated by Django 5.0 on 2026-04-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_suspended_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="previous_login",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
