# Generated by Django 5.0 on 2026-04-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_previous_login"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="previous_login",
        ),
    ]
