# Generated by Django 5.0 on 2026-01-30 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SwipeListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("donation", "Donation"), ("request", "Request")],
                        max_length=10,
                    ),
                ),
                (
                    "campus",
                    models.CharField(
                        choices=[("RH", "Rose Hill"), ("LC", "Lincoln Center")],
                        max_length=2,
                    ),
                ),
                ("dining_hall", models.CharField(blank=True, max_length=100)),
                ("quantity", models.IntegerField(default=1)),
                ("available_date", models.DateField()),
                ("available_time", models.TimeField(blank=True, null=True)),
                ("meeting_location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SwipeMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_conversation_id",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("donor_confirmed", models.BooleanField(default=False)),
                ("requester_confirmed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "donation_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation_matches",
                        to="swipes.swipelisting",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_matches",
                        to="swipes.swipelisting",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="swipelisting",
            index=models.Index(
                fields=["status", "type", "campus"],
                name="swipes_swip_status_cbe918_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="swipelisting",
            index=models.Index(
                fields=["user", "status"], name="swipes_swip_user_id_868e7f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swipelisting",
            index=models.Index(
                fields=["available_date"], name="swipes_swip_availab_8729a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swipematch",
            index=models.Index(
                fields=["donor", "status"], name="swipes_swip_donor_i_209f33_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swipematch",
            index=models.Index(
                fields=["requester", "status"], name="swipes_swip_request_b56816_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swipematch",
            index=models.Index(
                fields=["status", "created_at"], name="swipes_swip_status_25afec_idx"
            ),
        ),
    ]
