# Generated by Django 5.0 on 2026-04-03 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="image",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
