# Generated by Django 5.0 on 2026-04-03 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_comment_likes_count_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
    ]
