# Generated by Django 5.0 on 2026-04-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0005_postview"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
