# Generated by Django 5.0 on 2026-04-04 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0007_add_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="is_seen_by_post_owner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="postlike",
            name="is_seen_by_post_owner",
            field=models.BooleanField(default=False),
        ),
    ]
